name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        github_token: ${{ secrets.github_token }}
        args: "-p always"
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}
    - name: install dependencies
      run: npm install --legacy-peer-deps
    - name: build
      run: npm run linux 

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        github_token: ${{ secrets.github_token }}
        args: "-p always"
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}
    - name: install dependencies
      run: npm install --legacy-peer-deps
    - name: build
      run: npm run win

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        github_token: ${{ secrets.github_token }}
        args: "-p always"
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}
    - name: install dependencies
      run: npm install --legacy-peer-deps
    - name: build
      run: npm run mac   
