name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - name: install dependencies
      run: npm install --legacy-peer-deps
    - name: build
      run: npm run linux