name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - name: install dependencies
      run: npm install --legacy-peer-deps --force
    - name: build
      run: npm run linux